
#https://www.digitalocean.com/community/tutorials/docker-explained-how-to-containerize-and-use-nginx-as-a-proxy


FROM ubuntu:16.04
#FROM debian:stretch-slim

MAINTAINER Areg Sarkissian

RUN set -x \
# update the package manager
&& apt-get update \
# install nginx
&& apt-get install -y nginx \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
# forward request and error logs to docker log collector
&& ln -sf /dev/stdout /var/log/nginx/access.log \
&& ln -sf /dev/stderr /var/log/nginx/error.log

# Remove the default Nginx configuration file
#&& rm -v /etc/nginx/nginx.conf

# copy our custom configuration file to /etc/nginx/
# will overwrite existing nginx.conf file
COPY nginx.conf /etc/nginx/

# copy static our static content to the nginx   
# static content root as specifed in nginx.conf 
COPY index.html /etc/nginx/html/public/

# Change default stop signal from SIGTERM to SIGQUIT
STOPSIGNAL SIGQUIT

EXPOSE 80

CMD ["nginx","-g", "daemon off;"]

#####
###shakeyshane
#FROM nginx:1.12.2-alpine
#ADD vhost.conf /etc/nginx/conf.d/default.conf
#COPY public /var/www/public
#####
###nginx:1.12.2-alpine last lines
# forward request and error logs to docker log collector
#&& ln -sf /dev/stdout /var/log/nginx/access.log \
#&& ln -sf /dev/stderr /var/log/nginx/error.log
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf
#EXPOSE 80
#STOPSIGNAL SIGTERM
#CMD ["nginx", "-g", "daemon off;"]